# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Momex
tagline:          'Projectes d''electrònica en català'
url:              http://www.momex.cat
baseurl:          /

author:
  name:           'Xavier Morales'
  url:            https://www.momex.cat
  email:          morales.xavier@momex.cat

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/momex/momex.github.io.git

trans:
  ca:
    desc: "Projectes d'electrònica relacionats amb Harley Davidson i d'altres de caire DIY domèstic."
    home: "Inici"
    cont: "Contacte"
    ghpro: "Projecte GitHub"
  en:
    desc: "Electronic projects related to Harley Davidson and domestic DYI.                         "
    home: "Home"
    cont: "Contact"
    ghpro: "GitHub project"
