# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Momex
tagline:          'Projectes d'electrònica en català'
description:      'Exposició del codi font emprat per alguns projectes d'electrònica relacionats amb Harley Davidson i domèstics.'
url:              http://www.momex.cat
baseurl:          /

author:
  name:           'Xavier Morales'
  url:            https://www.momex.cat

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/momex/momex.github.io.git
