# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Pagination
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Setup
title:            Momex
name:            Momex
description: HD, Electronics and more.
url:              http://www.momex.cat
baseurl:          /

author:
  name:           'Xavier Morales'
  url:            https://www.momex.cat
  email:          morales.xavier@momex.cat

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/momex/momex.github.io.git

trans:
  ca:
    desc: "Projectes d'electrònica relacionats amb Harley Davidson i d'altres de caire DIY domèstic."
    home: "Inici"
    about: "Sobre mi"
    related: "Posts similars amb la categoria"
    arxiu: "Arxiu"
    cont: "Contacte"
    ghpro: "Projecte GitHub"
    tagline: "Projectes d'electrònica i altres"
  en:
    desc: "Electronic projects related to Harley Davidson and domestic DYI.                         "
    home: "Home"
    about: "About"
    related: "Related Posts with similar category"
    arxiu: "Archive"
    cont: "Contact"
    ghpro: "GitHub project"
    tagline: "Electronic projects and others"
